what leverage do you offer, We offer up to 1:200 leverage on Forex.
what products can I trade, you can trade Forex; Indices; Precious Metals; Energies and Crypto Currencies.
what should I do if I cannot place or close a trade, Please provide more information so we can assist you better.
how much is one standard lot equivilant to, 1 Standard Lot on EURUSD is equivilant to 100,000 EUR.
what are pending orders, A pending order is an instruction to buy or sell an instrument when certain preconditions specified by the trader are met.
what are swap free accounts, Swap Free is an option to have an account free from fees. It means you will neither receive nor pay the swap (fee).
what are the different type of pending orders, Buy Limit; Buy Stop; Sell Limit; Sell Stop; Buy Stop Limit; Sell Stop Limit.
what is a pip, Pip is an acronym for "percentage in point" or "price interest point." A pip is the smallest price move that an exchange rate can make based on forex market convention. Most currency pairs are priced out to four decimal places and the pip change is the last (fourth) decimal point. A pip is thus equivalent to 1/100 of 1% or one basis point.
what is leverage, Leverage results from using borrowed capital as a funding source when investing to expand the firm's asset base and generate returns on risk capital. Leverage is an investment strategy of using borrowed money—specifically; the use of various financial instruments or borrowed capital—to increase the potential return of an investment.
what is margin call, A margin call is the term used to describe the alert sent to a trader to notify them that the capital in their account has fallen below the minimum amount needed to keep a position open. A margin call can mean that the trader has to put up additional funds to balance the account; or close positions to reduce the maintenance margin required.
what is margin, In trading; margin is the funds required to open and maintain a leveraged position.
what is slippage, Slippage refers to the difference between the expected price of a trade and the price at which the trade is executed. Slippage can occur at any time but is most prevalent during periods of higher volatility when market orders are used. It can also occur when a large order is executed but there isn't enough volume at the chosen price to maintain the current bid/ask spread.
what is spread, In finance, the spread is the difference in price between the buy (bid) and sell (offer) prices quoted for an asset.
what is stop loss, A Stop Loss is an order which allows a trader to close a position when their chosen instrument reaches a certain price. Stop Loss parameters can be set before or after the opening of a position. A stop loss allows the trader to avoid excess losses by automatically closing a position. The obligatory condition of setting up a stop loss is that the financial instrument’s price should not be lower than the current market price when selling and not higher when buying.
what is swap, A Swap is the difference in credit interest rates for currencies used in trades. The interest is added (if it is positive) to the account or taken from it (if negative) when a trading position is left open overnight.
what is take profit, Take profit is a trading command which allows profit to be fixed to a certain amount when the price reaches a certain level. This command helps to reduce risks. If a trader sets up a take profit command on a certain trading instrument; when the price of the instrument reached the specified price level; the position will be closed automatically. A take profit command can be set up at any time during an open position.
what is the minimum amount I can deposit, the minimum amount you can start with is 300$.
when can I start trading, you can start trading after your trading account is successfully funded and your KYC documents are fully approved.
do you allow the use of eas, Yes; we do allow the use of EA's as long as they are not againest the trading terms and conditions.
are my funds safe with you, Yes; you funds are kept in our fully secured and segregated client's account. 
are my personal details secure with you, Yes; security of your personal details are very important to use and we took various meassures to make sure they are safe and secure.
can I change the leverage of my account, Yes; you can request to change your leverage from 1:1 up to 1:200.
can I change my demo account leverage, Yes; you can request to change your leverage from 1:1 up to 1:200.
can I delete trades from my demo account history, No; unfortunatly is not possible to delete any order either from real or demo account.
can I have a demo and real account at the same time, Yes; you can have demo account and real account at the same time.
do I need to download any software before I start trading, Yes; you should download our MT5 platform according to your device of choice in order to be able to trade.
do you offer demo account, Yes; we do offer demo accounts.
how long does it take to open a trading account, Opening a trading account takes a few second but funding the account might take from a few minutes to a few days depending on your funding methods.
I have forgotten my trading account password. what should I do, You should make a request for changing of trading account password from your clientzone.
what documents are required to open an account, You need to upload a valid Proof of identity – passport; national identity card or driving license and Proof of residence not older than 6 months– bank/card statement or utility bill. Examples of documents which can be provided are: Water/gas/electric/internet/telephone bill.
can I renew my demo account, Demo accounts last for 30 days after sign up. Afterward, you will not be able to log in using the demo account credentials. Demo renewals are not available at this time.
how long does a demo account last, Demo accounts last for 30 days after signup. Afterward, you will not be able to log in using the demo account credentials.
are there any data exchange fees associated with forex trading, We does not charge data exchange fees. However; you may incur a financing/rollover charge(Swap) if you hold your positions overnight.
do I need to pay taxes on my trades and transactions, Please contact a tax professional for information on the tax situation in your country.
what is forex, Forex, also known as foreign exchange or currency trading; is the buying of one currency by simultaneously selling another. Forex traders attempt to profit by speculating on the direction the currency exchange rates will go in the future.
when is the forex market open for trading, You can trade forex 24 hours a day, five days a week.
what forex markets are available to trade, You can trade 80+ currency pairs in our trading platforms.
are there any data/exchange fees associated with forex trading, We does not charge data or exchange fees on forex trades. We are compensated via the spread; which is the difference between the bid and ask.
how are metals traded, Gold and silver are traded as spot while copper; palladium and platinum are traded as CFD futures.
what are the markets for spot gold and silver, Currently we offer gold as XAU/USD; XAU/EUR; and XAU/AUD. The symbols for spot silver are XAG/USD; and XAG/EUR.
is there an expiry date on spot gold and silver, There is no expiry date when trading spot gold and silver. As long as you maintain the required margin; your position will remain open until you choose to close it. As with forex positions; open gold and silver positions automatically roll forward to the next day's value date following the close of NY trading at 1700 ET.
what is the minimum lot size for spot gold and silver, The minimum lot size for gold is 0.01. and the minimum for silver is 0.01 as well.
can I place trades over the phone, Yes, simply use our MT5 platform for your mobile device.
why was my position closed, You are responsible for monitoring your account and maintaining the required margin at all times to support your open positions. If at any point; the equity available drops below the level of margin required; you will be subject to liquidation. If you are still unsure why your position was closed, please contact us.
can my account go negative, While our margin requirements; closeout levels and real-time margin system are designed to limit your trading losses; you do risk incurring losses greater than your account balance; especially during periods of extreme market volatility. For this reason; we strongly encourage you to manage your use of leverage carefully.
what is rollover, A rollover (also known as a financing charge or swap rate) is the simultaneous closing of an open position for today's value date and the opening of the same position for the next day's value date at a price reflecting the interest rate differential between the two currencies. Each currency pair will have two rollover rates: one for short positions; another for long positions. Depending on the difference; your account will either be debited or credited a certain amount based on the rollover rate.